package sheenrox82.RioV.src.util;

import java.util.Arrays;

import net.minecraft.client.Minecraft;
import net.minecraft.world.biome.BiomeGenBase;
import net.minecraftforge.common.MinecraftForge;
import net.minecraftforge.common.config.Configuration;
import sheenrox82.RioV.src.base.Config;
import sheenrox82.RioV.src.base.Crafting;
import sheenrox82.RioV.src.base.TheMistsOfRioV;
import sheenrox82.RioV.src.content.Biomes;
import sheenrox82.RioV.src.content.Enchantments;
import sheenrox82.RioV.src.content.EntityLoader;
import sheenrox82.RioV.src.content.RioVBlocks;
import sheenrox82.RioV.src.content.RioVItems;
import sheenrox82.RioV.src.event.ConfigChanges;
import sheenrox82.RioV.src.event.Events;
import sheenrox82.RioV.src.gui.GuiEosBar;
import sheenrox82.RioV.src.handler.FuelHandler;
import sheenrox82.RioV.src.handler.packet.PacketHandler;
import sheenrox82.RioV.src.handler.packet.PacketPipeline;
import sheenrox82.RioV.src.recipe.AnvilCraftingManager;
import sheenrox82.RioV.src.registries.HarvestLevelRegistry;
import sheenrox82.RioV.src.tileentity.TileEntityFlag;
import sheenrox82.RioV.src.tileentity.TileEntityInfuser;
import sheenrox82.RioV.src.world.WorldGen;
import sheenrox82.RioV.src.world.provider.WorldProviderBlindOasis;
import sheenrox82.RioV.src.world.provider.WorldProviderFlamonor;
import sheenrox82.RioV.src.world.provider.WorldProviderSanctuatite;
import sheenrox82.RioV.src.world.provider.WorldProviderVaeryn;
import cpw.mods.fml.common.FMLCommonHandler;
import cpw.mods.fml.common.ModMetadata;
import cpw.mods.fml.common.event.FMLInitializationEvent;
import cpw.mods.fml.common.event.FMLPostInitializationEvent;
import cpw.mods.fml.common.event.FMLPreInitializationEvent;
import cpw.mods.fml.common.network.NetworkRegistry;
import cpw.mods.fml.common.registry.GameRegistry;

public class Registry 
{
	public static int render = 3;
	public static final PacketPipeline packetPipeline = new PacketPipeline();

	public static void preInit(FMLPreInitializationEvent initEvent)
	{		
		TheMistsOfRioV.getInstance().modLoaded = false;
		/**Inits and Regs**/
		LogHelper.info("Starting... //START PRE-INITIALIZATION");
		LogHelper.info("Sounds loaded.");
		FMLCommonHandler.instance().bus().register(new ConfigChanges());
		TheMistsOfRioV.commonProxy.init();
		ModMetadata data = initEvent.getModMetadata();
		data.autogenerated = false;
		data.modId = Util.MOD_ID;
		data.name = Util.MOD_NAME;
		data.logoFile = "/assets/riov/textures/misc/RioV.png";
		data.version = (Util.VERSION);
		data.url = "http://www.minecraftforum.net/user/630621-sheenrox82/";
		data.authorList = Arrays.asList(new String[] {"sheenrox82"});
		data.description = Util.MOD_NAME + " - The imagined world is called RioV, " +
				"in the year of 1301 DoC (Death of Carigon.), the land of RioV is " +
				"filled with Nizonians. A native creature that are basically giant beasts. " +
				"In 1278 DoC the Natives found a new threat across the land called humans, " +
				"another wild creature. Since then, the races have been weakened and new races have " +
				"arrived, such as the dark elves. There is a myth that in 1610 a monster called a " +
				"Soverian Overlord will destroy the land of RioV and leave it in ashes. " +
				"This is The Mists of RioV.";
		LogHelper.info("mcmod.info data initiated.");
		Config.initialize(initEvent);
		syncConfig();
		LogHelper.info("Config loaded.");
		MinecraftForge.EVENT_BUS.register(new Events());
		LogHelper.info("Events registered.");
		RioVItems.add();
		RioVBlocks.add();
		Crafting.add();
		Biomes.add();
		Enchantments.add();
		LogHelper.info("Content added.");
		HarvestLevelRegistry.addHarvestLevels();
		LogHelper.info("Some stats initiated.");
		GameRegistry.registerFuelHandler(new FuelHandler());
		GameRegistry.registerTileEntity(TileEntityInfuser.class, "Infuser");
		GameRegistry.registerTileEntity(TileEntityFlag.class, "Flag");
		GameRegistry.registerWorldGenerator(new WorldGen(), 3);
		NetworkRegistry.INSTANCE.registerGuiHandler(TheMistsOfRioV.getInstance(), TheMistsOfRioV.getInstance().guiHandler);
		MethodUtil.registerDimension(Config.blindOasisID, WorldProviderBlindOasis.class);
		MethodUtil.registerDimension(Config.vaerynID, WorldProviderVaeryn.class);
		MethodUtil.registerDimension(Config.flamonorID, WorldProviderFlamonor.class);
		MethodUtil.registerDimension(Config.sanctuatiteID, WorldProviderSanctuatite.class);
		AnvilCraftingManager.instance = new AnvilCraftingManager();
		LogHelper.info("Core data registered. //END PRE-INITIALIZATION");
	}

	public static void init(FMLInitializationEvent init)
	{		
		LogHelper.info("Other shit is registering. //START INITIALIZATION");
		TheMistsOfRioV.commonProxy.cape();
		LogHelper.info("Adding special capes. ;)");
		TheMistsOfRioV.commonProxy.registerItemRenderers();
		LogHelper.info("Item renderers registered.");
		EntityLoader.add();
		LogHelper.info("Entity data registering...");
		EntityLoader.addOverworldSpawning();
		EntityLoader.addNetherSpawning();
		EntityLoader.addEndSpawning();
		EntityLoader.addDimensionSpawning();
		LogHelper.info("Entity data registered.");
		ExpansionChecker.check();
		LogHelper.info("Checking for expansions...");
		BiomeGenBase.extremeHills.theBiomeDecorator.treesPerChunk = 15;
		BiomeGenBase.plains.theBiomeDecorator.treesPerChunk = 1;
		BiomeGenBase.plains.theBiomeDecorator.bigMushroomsPerChunk = 1;
		BiomeGenBase.plains.theBiomeDecorator.flowersPerChunk = 20;
		packetPipeline.initialise();
		LogHelper.info("Packets registering...");
		LogHelper.info("Packets registered.");
		LogHelper.info("Other shit is registered. //END INITIALIZATION");
	}

	public static void postInit(FMLPostInitializationEvent postInit)
	{
		LogHelper.info("Almost done initializing. //START POST-INITIALIZATION");
		packetPipeline.postInitialise();
		LogHelper.info("Packets post-registered.");

		if (FMLCommonHandler.instance().getEffectiveSide().isClient())
		{
			MinecraftForge.EVENT_BUS.register(new GuiEosBar(Minecraft.getMinecraft()));
			LogHelper.info("Eos bar registered.");
		}

		Config.initPost();
		LogHelper.info("Mod loaded! Sup. //END POST-INITIALIZATION");
		TheMistsOfRioV.getInstance().modLoaded = true;
	}
	
	public static void syncConfig() 
	{
        Config.EOS = Config.config.getBoolean("Use the purple Eos bar instead of text?", Configuration.CATEGORY_GENERAL, Config.EOS, "// Boolean");
        Config.showToolInfo = Config.config.getBoolean("Show Tool Info?", Configuration.CATEGORY_GENERAL, Config.showToolInfo, "// Boolean");
        Config.allowBreathing = Config.config.getBoolean("Allow Mob Breathing Sounds? (CLIENT SIDE)", Configuration.CATEGORY_GENERAL, Config.allowBreathing, "// Boolean");
        Config.deadBodies = Config.config.getBoolean("Allow Dead Bodies for mobs?", Configuration.CATEGORY_GENERAL, Config.deadBodies, "// Boolean");
        Config.runCapes = Config.config.getBoolean("Allow RioV Capes to initialize?", Configuration.CATEGORY_GENERAL, Config.runCapes, "// Boolean");

        if(Config.config.hasChanged())
        {
        	Config.config.save();
        }
    }
}
