package sheenrox82.RioV.src.content;

import net.minecraft.block.material.Material;
import net.minecraft.init.Blocks;
import net.minecraft.item.Item;
import net.minecraft.item.Item.ToolMaterial;
import net.minecraft.item.ItemArmor.ArmorMaterial;
import net.minecraftforge.common.util.EnumHelper;
import sheenrox82.RioV.src.item.RioVActivators;
import sheenrox82.RioV.src.item.RioVArmor;
import sheenrox82.RioV.src.item.RioVAxe;
import sheenrox82.RioV.src.item.RioVBag;
import sheenrox82.RioV.src.item.RioVConsumable;
import sheenrox82.RioV.src.item.RioVDoor;
import sheenrox82.RioV.src.item.RioVDrinkable;
import sheenrox82.RioV.src.item.RioVExplosives;
import sheenrox82.RioV.src.item.RioVItem;
import sheenrox82.RioV.src.item.RioVPickaxe;
import sheenrox82.RioV.src.item.RioVPotions;
import sheenrox82.RioV.src.item.RioVSpade;
import sheenrox82.RioV.src.item.RioVSummoners;
import sheenrox82.RioV.src.item.RioVVoidHolder;
import sheenrox82.RioV.src.item.RioVWand;
import sheenrox82.RioV.src.item.RioVWeapon;
import sheenrox82.RioV.src.item.unique.ItemBowOfWurTun;
import sheenrox82.RioV.src.item.unique.ItemEnforcedBowOfWurTun;
import sheenrox82.RioV.src.item.unique.ItemGuide;
import sheenrox82.RioV.src.item.unique.ItemTasaravChestplate;
import sheenrox82.RioV.src.item.unique.ItemTasaravHelmet;
import sheenrox82.RioV.src.item.unique.ItemVraviniteBow;
import sheenrox82.RioV.src.proxy.CommonProxy;
import sheenrox82.RioV.src.util.MethodUtil;

public class RioVItems 
{
	public static final int render = CommonProxy.addArmor("armor");

	static ToolMaterial Amethyst = EnumHelper.addToolMaterial("Amethyst", 3, 400, 5F, 4, 8);
	static ToolMaterial InfusedAmethyst = EnumHelper.addToolMaterial("InfusedAmethyst", 3, 500, 9F, 5, 9);
	static ToolMaterial Onyx = EnumHelper.addToolMaterial("Onyx", 3, 600, 10F, 5, 10);
	static ToolMaterial InfusedOnyx = EnumHelper.addToolMaterial("InfusedOnyx", 4, 700, 11F, 6, 11);
	static ToolMaterial Agonite = EnumHelper.addToolMaterial("Agonite", 8, 1000, 9F, 3, 14);
	static ToolMaterial Dragon = EnumHelper.addToolMaterial("Dragon", 9, 3000, 15F, 10, 15);
	static ToolMaterial Daetori = EnumHelper.addToolMaterial("Daetori", 2, 500, 5F, 9, 12);
	static ToolMaterial Sorrow = EnumHelper.addToolMaterial("Sorrow", 2, 700, 5F, 10, 13);
	static ToolMaterial AxeOfAunTun = EnumHelper.addToolMaterial("AxeOfAunTun", 2, 2500, 5F, 18, 16);
	static ToolMaterial UltraAxeOfAunTun = EnumHelper.addToolMaterial("UltraAxeOfAunTun", 2, 5000, 5F, 26, 30);
	static ToolMaterial Vulron = EnumHelper.addToolMaterial("Vulron", 6, 200, 9F, 6, 12);
	static ToolMaterial InfusedDragon = EnumHelper.addToolMaterial("InfusedDragon", 11, 3400, 18F, 11, 16);
	static ToolMaterial Galokin = EnumHelper.addToolMaterial("Galokin", 4, 400, 6F, 6, 12);
	static ToolMaterial Flame = EnumHelper.addToolMaterial("Flame", 6, 900, 9F, 7, 16);
	static ToolMaterial Blindonite = EnumHelper.addToolMaterial("Blindonite", 4, 400, 6F, 5, 14);
	static ToolMaterial InfusedBlindonite = EnumHelper.addToolMaterial("InfusedBlindonite", 5, 600, 8F, 7, 15);
	static ToolMaterial Glimmerwood = EnumHelper.addToolMaterial("Glimmerwood", 2, 250, 4F, 2, 20);
	static ToolMaterial CherryBlossom = EnumHelper.addToolMaterial("CherryBlossom", 2, 100, 2F, 0, 20);
	static ToolMaterial Aleris = EnumHelper.addToolMaterial("Aleris", 14, 2400, 14F, 16, 21);
	static ToolMaterial InfusedVravinite = EnumHelper.addToolMaterial("InfusedVravinite", 13, 1000, 13F, 11, 12);
	static ToolMaterial Vravinite = EnumHelper.addToolMaterial("Vravinite", 12, 900, 13F, 10, 12);

	static ArmorMaterial InfusedAmethystArmorMaterial = EnumHelper.addArmorMaterial("INFUSEDAMETHYST", 17, new int[] {4, 6, 6, 4}, 20);
	static ArmorMaterial InfusedOnyxArmorMaterial = EnumHelper.addArmorMaterial("INFUSEDONYX", 18, new int[] {5, 6, 6, 5}, 20);
	static ArmorMaterial Magic = EnumHelper.addArmorMaterial("MAGIC", 2, new int[] {1, 1, 1, 1}, 28);
	static ArmorMaterial InfusedDragonArmorMaterial = EnumHelper.addArmorMaterial("INFUSEDDRAGON", 39, new int[] {4, 6, 6, 4}, 20);
	static ArmorMaterial DragonArmorMaterial = EnumHelper.addArmorMaterial("DRAGON", 37, new int[] {4, 6, 6, 4}, 20);
	static ArmorMaterial AunTunArmorMaterial = EnumHelper.addArmorMaterial("AUNTUN", 40, new int[] {3, 8, 6, 3}, 20);
	static ArmorMaterial GarnetArmorMaterial = EnumHelper.addArmorMaterial("GARNET", 22, new int[] {4, 5, 6, 4}, 20);
	static ArmorMaterial AmethystArmorMaterial = EnumHelper.addArmorMaterial("AMETHYST", 15, new int[] {3, 5, 6, 3}, 20);
	static ArmorMaterial OnyxArmorMaterial = EnumHelper.addArmorMaterial("ONYX", 16, new int[] {4, 5, 6, 4}, 20);
	static ArmorMaterial MythrilArmorMaterial = EnumHelper.addArmorMaterial("MYTHRIL", 36, new int[] {4, 8, 6, 4}, 20);
	static ArmorMaterial GalokinArmorMaterial = EnumHelper.addArmorMaterial("GALOKIN", 33, new int[] {3, 8, 6, 3}, 20);
	static ArmorMaterial FlameArmorMaterial = EnumHelper.addArmorMaterial("FLAME", 30, new int[] {4, 5, 6, 4}, 20);
	static ArmorMaterial BlindoniteArmorMaterial = EnumHelper.addArmorMaterial("BLINDONITE", 20, new int[] {3, 4, 6, 3}, 20);
	static ArmorMaterial InfusedBlindoniteArmorMaterial = EnumHelper.addArmorMaterial("INFUSEDBLINDONITE", 23, new int[] {3, 4, 6, 3}, 20);
	static ArmorMaterial AlerisArmorMaterial = EnumHelper.addArmorMaterial("ALERIS", 48, new int[] {5, 8, 6, 5}, 20);
	static ArmorMaterial InfusedVraviniteArmorMaterial = EnumHelper.addArmorMaterial("VRAVINITE", 33, new int[] {4, 6, 6, 4}, 20);
	static ArmorMaterial VraviniteArmorMaterial = EnumHelper.addArmorMaterial("VRAVINITE", 32, new int[] {4, 6, 6, 4}, 20);
	static ArmorMaterial SupremeAunTunArmorMaterial = EnumHelper.addArmorMaterial("SUPREMEAUNTUN", 68, new int[] {7, 10, 9, 9}, 50);

	public static RioVArmor onyxHelmet = (RioVArmor)new RioVArmor(OnyxArmorMaterial, render, 0, "onyx", false).setUnlocalizedName("onyxHelmet");
	public static RioVArmor onyxChestplate = (RioVArmor)new RioVArmor(OnyxArmorMaterial, render, 1, "onyx", false).setUnlocalizedName("onyxChestplate");
	public static RioVArmor onyxLeggings = (RioVArmor)new RioVArmor(OnyxArmorMaterial, render, 2, "onyx", false).setUnlocalizedName("onyxLeggings");
	public static RioVArmor onyxBoots = (RioVArmor)new RioVArmor(OnyxArmorMaterial, render, 3, "onyx", false).setUnlocalizedName("onyxBoots");
	public static RioVArmor amethystHelmet = (RioVArmor)new RioVArmor(AmethystArmorMaterial, render, 0, "amethyst", false).setUnlocalizedName("amethystHelmet");
	public static RioVArmor amethystChestplate = (RioVArmor)new RioVArmor(AmethystArmorMaterial, render, 1, "amethyst", false).setUnlocalizedName("amethystChestplate");
	public static RioVArmor amethystLeggings = (RioVArmor)new RioVArmor(AmethystArmorMaterial, render, 2, "amethyst", false).setUnlocalizedName("amethystLeggings");
	public static RioVArmor amethystBoots = (RioVArmor)new RioVArmor(AmethystArmorMaterial, render, 3, "amethyst", false).setUnlocalizedName("amethystBoots");
	public static RioVArmor infusedOnyxHelmet = (RioVArmor)new RioVArmor(InfusedOnyxArmorMaterial, render, 0, "onyx", true).setUnlocalizedName("infusedOnyxHelmet");
	public static RioVArmor infusedOnyxChestplate = (RioVArmor)new RioVArmor(InfusedOnyxArmorMaterial, render, 1, "onyx", true).setUnlocalizedName("infusedOnyxChestplate");
	public static RioVArmor infusedOnyxLeggings = (RioVArmor)new RioVArmor(InfusedOnyxArmorMaterial, render, 2, "onyx", true).setUnlocalizedName("infusedOnyxLeggings");
	public static RioVArmor infusedOnyxBoots = (RioVArmor)new RioVArmor(InfusedOnyxArmorMaterial, render, 3, "onyx", true).setUnlocalizedName("infusedOnyxBoots");
	public static RioVArmor infusedAmethystHelmet = (RioVArmor)new RioVArmor(InfusedAmethystArmorMaterial, render, 0, "amethyst", true).setUnlocalizedName("infusedAmethystHelmet");
	public static RioVArmor infusedAmethystChestplate = (RioVArmor)new RioVArmor(InfusedAmethystArmorMaterial, render, 1, "amethyst", true).setUnlocalizedName("infusedAmethystChestplate");
	public static RioVArmor infusedAmethystLeggings = (RioVArmor)new RioVArmor(InfusedAmethystArmorMaterial, render, 2, "amethyst", true).setUnlocalizedName("infusedAmethystLeggings");
	public static RioVArmor infusedAmethystBoots = (RioVArmor)new RioVArmor(InfusedAmethystArmorMaterial, render, 3, "amethyst", true).setUnlocalizedName("infusedAmethystBoots");
	public static RioVArmor auntunHelmet = (RioVArmor)new RioVArmor(AunTunArmorMaterial, render, 0, "auntunminion", false).setUnlocalizedName("auntunHelmet");
	public static RioVArmor auntunChestplate = (RioVArmor)new RioVArmor(AunTunArmorMaterial, render, 1, "auntunminion", false).setUnlocalizedName("auntunChestplate");
	public static RioVArmor auntunLeggings = (RioVArmor)new RioVArmor(AunTunArmorMaterial, render, 2, "auntunminion", false).setUnlocalizedName("auntunLeggings");
	public static RioVArmor auntunBoots = (RioVArmor)new RioVArmor(AunTunArmorMaterial, render, 3, "auntunminion", false).setUnlocalizedName("auntunBoots");
	public static RioVArmor garnetHelmet = (RioVArmor)new RioVArmor(GarnetArmorMaterial, render, 0, "garnet", false).setUnlocalizedName("garnetHelmet");
	public static RioVArmor garnetChestplate = (RioVArmor)new RioVArmor(GarnetArmorMaterial, render, 1, "garnet", false).setUnlocalizedName("garnetChestplate");
	public static RioVArmor garnetLeggings = (RioVArmor)new RioVArmor(GarnetArmorMaterial, render, 2, "garnet", false).setUnlocalizedName("garnetLeggings");
	public static RioVArmor garnetBoots = (RioVArmor)new RioVArmor(GarnetArmorMaterial, render, 3, "garnet", false).setUnlocalizedName("garnetBoots");
	public static RioVArmor mythrilHelmet = (RioVArmor)new RioVArmor(MythrilArmorMaterial, render, 0, "mythril", false).setUnlocalizedName("mythrilHelmet");
	public static RioVArmor mythrilChestplate = (RioVArmor)new RioVArmor(MythrilArmorMaterial, render, 1, "mythril", false).setUnlocalizedName("mythrilChestplate");
	public static RioVArmor mythrilLeggings = (RioVArmor)new RioVArmor(MythrilArmorMaterial, render, 2, "mythril", false).setUnlocalizedName("mythrilLeggings");
	public static RioVArmor mythrilBoots = (RioVArmor)new RioVArmor(MythrilArmorMaterial, render, 3, "mythril", false).setUnlocalizedName("mythrilBoots");
	public static RioVArmor dragonHelmet = (RioVArmor)new RioVArmor(DragonArmorMaterial, render, 0, "dragon", false).setUnlocalizedName("dragonHelmet");
	public static RioVArmor dragonChestplate = (RioVArmor)new RioVArmor(DragonArmorMaterial, render, 1, "dragon", false).setUnlocalizedName("dragonChestplate");
	public static RioVArmor dragonLeggings = (RioVArmor)new RioVArmor(DragonArmorMaterial, render, 2, "dragon", false).setUnlocalizedName("dragonLeggings");
	public static RioVArmor dragonBoots = (RioVArmor)new RioVArmor(DragonArmorMaterial, render, 3, "dragon", false).setUnlocalizedName("dragonBoots");
	public static Item amethystSword = new RioVWeapon(Amethyst, false).setUnlocalizedName("amethystSword");
	public static Item infusedAmethystSword = new RioVWeapon(InfusedAmethyst, true).setUnlocalizedName("infusedAmethystSword");
	public static Item onyxSword = new RioVWeapon(Onyx, false).setUnlocalizedName("onyxSword");
	public static Item infusedOnyxSword = new RioVWeapon(InfusedOnyx, true).setUnlocalizedName("infusedOnyxSword");
	public static Item daetoriSword = new RioVWeapon(Daetori, false).setUnlocalizedName("daetoriSword");
	public static Item sorrowSword = new RioVWeapon(Sorrow, false).setUnlocalizedName("sorrowSword");
	public static Item axeOfAunTun = new RioVWeapon(AxeOfAunTun, false).setUnlocalizedName("axeOfAunTun");
	public static Item dragonSword = new RioVWeapon(Dragon, false).setUnlocalizedName("dragonSword");
	public static Item onyxPickaxe = new RioVPickaxe(Onyx, false).setUnlocalizedName("onyxPickaxe");
	public static Item onyxAxe = new RioVAxe(Onyx, false).setUnlocalizedName("onyxAxe");
	public static Item onyxShovel = new RioVSpade(Onyx, false).setUnlocalizedName("onyxShovel");
	public static Item amethystPickaxe = new RioVPickaxe(Amethyst, false).setUnlocalizedName("amethystPickaxe");
	public static Item amethystAxe = new RioVAxe(Amethyst, false).setUnlocalizedName("amethystAxe");
	public static Item amethystShovel = new RioVSpade(Amethyst, false).setUnlocalizedName("amethystShovel");
	public static Item infusedOnyxPickaxe = new RioVPickaxe(InfusedOnyx, true).setUnlocalizedName("infusedOnyxPickaxe");
	public static Item infusedOnyxAxe = new RioVAxe(InfusedOnyx, true).setUnlocalizedName("infusedOnyxAxe");
	public static Item infusedOnyxShovel = new RioVSpade(InfusedOnyx, true).setUnlocalizedName("infusedOnyxShovel");
	public static Item infusedAmethystPickaxe = new RioVPickaxe(InfusedAmethyst, true).setUnlocalizedName("infusedAmethystPickaxe");
	public static Item infusedAmethystAxe = new RioVAxe(InfusedAmethyst, true).setUnlocalizedName("infusedAmethystAxe");
	public static Item infusedAmethystShovel = new RioVSpade(InfusedAmethyst, true).setUnlocalizedName("infusedAmethystShovel");
	public static Item agonitePickaxe = new RioVPickaxe(Agonite, false).setUnlocalizedName("agonitePickaxe");
	public static Item dragonPickaxe = new RioVPickaxe(Dragon, false).setUnlocalizedName("dragonPickaxe");
	public static Item dragonAxe = new RioVAxe(Dragon, false).setUnlocalizedName("dragonAxe");
	public static Item dragonShovel = new RioVSpade(Dragon, false).setUnlocalizedName("dragonShovel");
	public static Item amethyst = new RioVItem().setUnlocalizedName("amethyst");
	public static Item onyx = new RioVItem().setUnlocalizedName("onyx");
	public static Item blackBone = new RioVItem().setUnlocalizedName("blackBone");
	public static Item orb = new RioVItem().setUnlocalizedName("orb");
	public static Item slateFragment = new RioVItem().setUnlocalizedName("slateFragment");
	public static Item garnet = new RioVItem().setUnlocalizedName("garnet");
	public static Item agonite = new RioVItem().setUnlocalizedName("agonite");
	public static Item darkMatter = new RioVExplosives().setUnlocalizedName("darkMatter");
	public static Item mythrilIngot = new RioVItem().setUnlocalizedName("mythrilIngot");
	public static Item dragonSoul = new RioVItem().setUnlocalizedName("dragonSoul");
	public static Item nironite = new RioVItem().setUnlocalizedName("nironite");
	public static Item burnedQuartz = new RioVItem().setUnlocalizedName("burnedQuartz");
	public static Item vulron = new RioVItem().setUnlocalizedName("vulron");
	public static Item darknessArrow = new RioVItem().setUnlocalizedName("darknessArrow");
	public static Item unfusedAxeOfAunTun = new RioVWeapon(Amethyst, false).setUnlocalizedName("unfusedAxeOfAunTun");
	public static Item halfFusedAxeOfAunTun = new RioVWeapon(Amethyst, false).setUnlocalizedName("halfFusedAxeOfAunTun");
	public static Item ambrosia = new RioVConsumable(3, 0, false).setUnlocalizedName("ambrosia");
	public static Item tomato = new RioVConsumable(4, 0, false).setUnlocalizedName("tomato");
	public static Item cookedHorseMeat = new RioVConsumable(5, 0, false).setUnlocalizedName("cookedHorseMeat");
	public static Item horseMeat = new RioVConsumable(1, 0, false).setUnlocalizedName("horseMeat");
	public static Item blackDurii = new RioVConsumable(4, 0, false).setUnlocalizedName("blackDurii");
	public static Item baseCrystal = new RioVItem().setUnlocalizedName("baseCrystal");
	public static Item terronCrystal = new RioVSummoners().setUnlocalizedName("terronCrystalCrystal");
	public static Item demonAngelCrystal = new RioVSummoners().setUnlocalizedName("demonAngelCrystal");
	public static Item auntunSummoner = new RioVSummoners().setUnlocalizedName("auntunSummoner");
	public static Item khuulisScythe = new RioVWeapon(Onyx, false).setUnlocalizedName("khuulisScythe");
	public static Item bowOfWurTun = new ItemBowOfWurTun().setUnlocalizedName("bowOfWurTun");
	public static Item wineGlass = new RioVItem().setUnlocalizedName("wineGlass");
	public static Item potionGlass = new RioVItem().setUnlocalizedName("potionGlass");
	public static Item grapes = new RioVConsumable(3, 0, false).setUnlocalizedName("grapes");
	public static Item wine = new RioVDrinkable(3, 0, false).setUnlocalizedName("wine");
	public static Item greenApple = new RioVConsumable(2, 0, false).setUnlocalizedName("greenApple");
	public static Item spicedWine = new RioVDrinkable(4, 0, false).setUnlocalizedName("spicedWine");
	public static Item pepper = new RioVConsumable(1, 0, false).setUnlocalizedName("pepper");
	public static Item pepperSpices = new RioVConsumable(1, 0, false).setUnlocalizedName("pepperSpices");
	public static Item manchet = new RioVConsumable(4, 0, false).setUnlocalizedName("manchet");
	public static Item cherry = new RioVConsumable(6, 0, false).setUnlocalizedName("cherry");
	public static Item vaiziCurrency = new RioVItem().setUnlocalizedName("vaiziCurrency");
	public static Item galokinSword = new RioVWeapon(Galokin, false).setUnlocalizedName("galokinSword");
	public static RioVArmor galokinHelmet = (RioVArmor)new RioVArmor(GalokinArmorMaterial, render, 0, "galokin", false).setUnlocalizedName("galokinHelmet");
	public static RioVArmor galokinChestplate = (RioVArmor)new RioVArmor(GalokinArmorMaterial, render, 1, "galokin", false).setUnlocalizedName("galokinChestplate");
	public static RioVArmor galokinLeggings = (RioVArmor)new RioVArmor(GalokinArmorMaterial, render, 2, "galokin", false).setUnlocalizedName("galokinLeggings");
	public static RioVArmor galokinBoots = (RioVArmor)new RioVArmor(GalokinArmorMaterial, render, 3, "galokin", false).setUnlocalizedName("galokinBoots");
	public static Item galokinCrystal = new RioVItem().setUnlocalizedName("galokinCrystal");
	public static Item clothOfMagic = new RioVItem().setUnlocalizedName("clothOfMagic");
	public static RioVArmor magickaHelmet = (RioVArmor)new RioVArmor(Magic, render, 0, "magic", true).setUnlocalizedName("magickaHelmet");
	public static RioVArmor magickaChestplate = (RioVArmor)new RioVArmor(Magic, render, 1, "magic", true).setUnlocalizedName("magickaChestplate");
	public static RioVArmor magickaLeggings = (RioVArmor)new RioVArmor(Magic, render, 2, "magic", true).setUnlocalizedName("magickaLeggings");
	public static RioVArmor magickaBoots = (RioVArmor)new RioVArmor(Magic, render, 3, "magic", true).setUnlocalizedName("magickaBoots");
	public static Item theDarknessCrystal = new RioVSummoners().setUnlocalizedName("theDarknessCrystal");
	public static Item ingotOfFlame = new RioVItem().setUnlocalizedName("ingotOfFlame");
	public static Item swordOfFlame = new RioVWeapon(Flame, false).setUnlocalizedName("swordOfFlame");
	public static Item purpleFeather = new RioVItem().setUnlocalizedName("purpleFeather");
	public static RioVArmor helmetOfFlame = (RioVArmor)new RioVArmor(FlameArmorMaterial, render, 0, "flame", false).setUnlocalizedName("helmetOfFlame");
	public static RioVArmor chestplateOfFlame = (RioVArmor)new RioVArmor(FlameArmorMaterial, render, 1, "flame", false).setUnlocalizedName("chestplateOfFlame");
	public static RioVArmor leggingsOfFlame = (RioVArmor)new RioVArmor(FlameArmorMaterial, render, 2, "flame", false).setUnlocalizedName("leggingsOfFlame");
	public static RioVArmor bootsOfFlame = (RioVArmor)new RioVArmor(FlameArmorMaterial, render, 3, "flame", false).setUnlocalizedName("bootsOfFlame");
	public static RioVArmor infusedDragonHelmet = (RioVArmor)new RioVArmor(InfusedDragonArmorMaterial, render, 0, "dragon", true).setUnlocalizedName("infusedDragonHelmet");
	public static RioVArmor infusedDragonChestplate = (RioVArmor)new RioVArmor(InfusedDragonArmorMaterial, render, 1, "dragon", true).setUnlocalizedName("infusedDragonChestplate");
	public static RioVArmor infusedDragonLeggings = (RioVArmor)new RioVArmor(InfusedDragonArmorMaterial, render, 2, "dragon", true).setUnlocalizedName("infusedDragonLeggings");
	public static RioVArmor infusedDragonBoots = (RioVArmor)new RioVArmor(InfusedDragonArmorMaterial, render, 3, "dragon", true).setUnlocalizedName("infusedDragonBoots");
	public static Item infusedDragonSword = new RioVWeapon(InfusedDragon, true).setUnlocalizedName("infusedDragonSword");
	public static Item infusedDragonPickaxe = new RioVPickaxe(InfusedDragon, true).setUnlocalizedName("infusedDragonPickaxe");
	public static Item infusedDragonAxe = new RioVAxe(InfusedDragon, true).setUnlocalizedName("infusedDragonAxe");
	public static Item infusedDragonShovel = new RioVSpade(InfusedDragon, true).setUnlocalizedName("infusedDragonShovel");
	public static Item enforcedBowOfWurTun = (new ItemEnforcedBowOfWurTun()).setUnlocalizedName("enforcedbowOfWurTun");
	public static Item blindonite = (new RioVItem()).setUnlocalizedName("blindonite");
	public static Item blindOasisActivator = (new RioVActivators()).setUnlocalizedName("blindOasisActivator");
	public static Item tefHelmet = (new RioVArmor(FlameArmorMaterial, render, 0, "tef", false)).setUnlocalizedName("tefHelmet");
	public static Item tefChestplate = (new RioVArmor(FlameArmorMaterial, render, 1, "tef", false)).setUnlocalizedName("tefChestplate");
	public static Item tefLeggings = (new RioVArmor(FlameArmorMaterial, render, 2, "tef", false)).setUnlocalizedName("tefLeggings");
	public static Item tefBoots = (new RioVArmor(FlameArmorMaterial, render, 3, "tef", false)).setUnlocalizedName("tefBoots");
	public static Item tefCrystal = (new RioVSummoners()).setUnlocalizedName("tefCrystal");
	public static Item blindoniteHelmet = (new RioVArmor(BlindoniteArmorMaterial, render, 0, "blindonite", false)).setUnlocalizedName("blindoniteHelmet");
	public static Item blindoniteChestplate = (new RioVArmor(BlindoniteArmorMaterial, render, 1, "blindonite", false)).setUnlocalizedName("blindoniteChestplate");
	public static Item blindoniteLeggings = (new RioVArmor(BlindoniteArmorMaterial, render, 2, "blindonite", false)).setUnlocalizedName("blindoniteLeggings");
	public static Item blindoniteBoots = (new RioVArmor(BlindoniteArmorMaterial, render, 3, "blindonite", false)).setUnlocalizedName("blindoniteBoots");
	public static Item blindonitePickaxe = (new RioVPickaxe(Blindonite, false)).setUnlocalizedName("blindonitePickaxe");
	public static Item blindoniteAxe = (new RioVAxe(Blindonite, false)).setUnlocalizedName("blindoniteAxe");
	public static Item blindoniteShovel = (new RioVSpade(Blindonite, false)).setUnlocalizedName("blindoniteShovel");
	public static Item blindoniteSword = (new RioVWeapon(Blindonite, false)).setUnlocalizedName("blindoniteSword");
	public static Item infusedBlindoniteHelmet = (new RioVArmor(InfusedBlindoniteArmorMaterial, render, 0, "blindonite", true)).setUnlocalizedName("infusedBlindoniteHelmet");
	public static Item infusedBlindoniteChestplate = (new RioVArmor(InfusedBlindoniteArmorMaterial, render, 1, "blindonite", true)).setUnlocalizedName("infusedBlindoniteChestplate");
	public static Item infusedBlindoniteLeggings = (new RioVArmor(InfusedBlindoniteArmorMaterial, render, 2, "blindonite", true)).setUnlocalizedName("infusedBlindoniteLeggings");
	public static Item infusedBlindoniteBoots = (new RioVArmor(InfusedBlindoniteArmorMaterial, render, 3, "blindonite", true)).setUnlocalizedName("infusedBlindoniteBoots");
	public static Item infusedBlindonitePickaxe = (new RioVPickaxe(InfusedBlindonite, true)).setUnlocalizedName("infusedBlindonitePickaxe");
	public static Item infusedBlindoniteAxe = (new RioVAxe(InfusedBlindonite, true)).setUnlocalizedName("infusedBlindoniteAxe");
	public static Item infusedBlindoniteShovel = (new RioVSpade(InfusedBlindonite, true)).setUnlocalizedName("infusedBlindoniteShovel");
	public static Item infusedBlindoniteSword = (new RioVWeapon(InfusedBlindonite, true)).setUnlocalizedName("infusedBlindoniteSword");
	public static Item vaerynActivator = (new RioVActivators()).setUnlocalizedName("vaerynActivator");
	public static Item glimmerwoodSticks = (new RioVItem()).setUnlocalizedName("glimmerwoodSticks");
	public static Item glimmerwoodPickaxe = (new RioVPickaxe(Glimmerwood, false)).setUnlocalizedName("glimmerwoodPickaxe");
	public static Item glimmerwoodAxe = (new RioVAxe(Glimmerwood, false)).setUnlocalizedName("glimmerwoodAxe");
	public static Item glimmerwoodShovel = (new RioVSpade(Glimmerwood, false)).setUnlocalizedName("glimmerwoodShovel");
	public static Item glimmerwoodSword = (new RioVWeapon(Glimmerwood, false)).setUnlocalizedName("glimmerwoodSword");
	public static Item blueMagicApple = (new RioVConsumable(8, 0, true)).setUnlocalizedName("blueApple");
	public static Item vraviniteBow = (new ItemVraviniteBow()).setUnlocalizedName("vraviniteBow");
	public static Item vraviniteArrow = (new RioVItem()).setUnlocalizedName("vraviniteArrow");
	public static Item vravinite = (new RioVItem()).setUnlocalizedName("vravinite");
	public static Item vraviniteHelmet = (new RioVArmor(VraviniteArmorMaterial, render, 0, "vravinite", false)).setUnlocalizedName("vraviniteHelmet");
	public static Item vraviniteChestplate = (new RioVArmor(VraviniteArmorMaterial, render, 1, "vravinite", false)).setUnlocalizedName("vraviniteChestplate");
	public static Item vraviniteLeggings = (new RioVArmor(VraviniteArmorMaterial, render, 2, "vravinite", false)).setUnlocalizedName("vraviniteLeggings");
	public static Item vraviniteBoots = (new RioVArmor(VraviniteArmorMaterial, render, 3, "vravinite", false)).setUnlocalizedName("vraviniteBoots");
	public static Item vravinitePickaxe = (new RioVPickaxe(Vravinite, false)).setUnlocalizedName("vravinitePickaxe");
	public static Item vraviniteAxe = (new RioVAxe(Vravinite, false)).setUnlocalizedName("vraviniteAxe");
	public static Item vraviniteShovel = (new RioVSpade(Vravinite, false)).setUnlocalizedName("vraviniteShovel");
	public static Item vraviniteSword = (new RioVWeapon(Vravinite, false)).setUnlocalizedName("vraviniteSword");
	public static Item glimmerwoodDoorItem = (new RioVDoor(Material.field_151568_F)).setUnlocalizedName("glimmerwoodDoorItem");
	public static Item flamonorActivator = (new RioVActivators()).setUnlocalizedName("flamonorActivator");
	public static Item drakiuz = (new RioVItem()).setUnlocalizedName("drakiuz");
	public static Item fireballWand = (new RioVWand(0, 1, 4)).setUnlocalizedName("fireballWand");
	public static Item cherryBlossomDoorItem = (new RioVDoor(Material.field_151570_A)).setUnlocalizedName("cherryBlossomDoorItem");
	public static Item cherryBlossomSticks = (new RioVItem()).setUnlocalizedName("cherryBlossomSticks");
	public static Item cherryBlossomPickaxe = (new RioVPickaxe(CherryBlossom, false)).setUnlocalizedName("cherryBlossomPickaxe");
	public static Item cherryBlossomAxe = (new RioVAxe(CherryBlossom, false)).setUnlocalizedName("cherryBlossomAxe");
	public static Item cherryBlossomShovel = (new RioVSpade(CherryBlossom, false)).setUnlocalizedName("cherryBlossomShovel");
	public static Item cherryBlossomSword = (new RioVWeapon(CherryBlossom, false)).setUnlocalizedName("cherryBlossomSword");
	public static Item potionGlassSanctuatite = (new RioVPotions(RioVBlocks.sanctuatiteMoving)).setUnlocalizedName("potionGlassSanctuatite");
	public static Item sanctuatiteActivator = (new RioVActivators()).setUnlocalizedName("sanctuatiteActivator");
	public static Item skywoodDoorItem = (new RioVDoor(Material.field_151571_B)).setUnlocalizedName("skywoodDoorItem");
	public static Item bloodDoorItem = (new RioVDoor(Material.field_151577_b)).setUnlocalizedName("bloodDoorItem");
	public static Item skywoodSticks = (new RioVItem()).setUnlocalizedName("skywoodSticks");
	public static Item skywoodPickaxe = (new RioVPickaxe(ToolMaterial.STONE, false)).setUnlocalizedName("skywoodPickaxe");
	public static Item skywoodAxe = (new RioVAxe(ToolMaterial.STONE, false)).setUnlocalizedName("skywoodAxe");
	public static Item skywoodShovel = (new RioVSpade(ToolMaterial.STONE, false)).setUnlocalizedName("skywoodShovel");
	public static Item skywoodSword = (new RioVWeapon(ToolMaterial.STONE, false)).setUnlocalizedName("skywoodSword");
	public static Item bloodSticks = (new RioVItem()).setUnlocalizedName("bloodSticks");
	public static Item bloodPickaxe = (new RioVPickaxe(ToolMaterial.WOOD, false)).setUnlocalizedName("bloodPickaxe");
	public static Item bloodAxe = (new RioVAxe(ToolMaterial.WOOD, false)).setUnlocalizedName("bloodAxe");
	public static Item bloodShovel = (new RioVSpade(ToolMaterial.WOOD, false)).setUnlocalizedName("bloodShovel");
	public static Item bloodSword = (new RioVWeapon(ToolMaterial.WOOD, false)).setUnlocalizedName("bloodSword");
	public static Item sanctuaryStonePickaxe = (new RioVPickaxe(ToolMaterial.IRON, false)).setUnlocalizedName("sanctuaryStonePickaxe");
	public static Item sanctuaryStoneAxe = (new RioVAxe(ToolMaterial.IRON, false)).setUnlocalizedName("sanctuaryStoneAxe");
	public static Item sanctuaryStoneShovel = (new RioVSpade(ToolMaterial.IRON, false)).setUnlocalizedName("sanctuaryStoneShovel");
	public static Item sanctuaryStoneSword = (new RioVWeapon(ToolMaterial.IRON, false)).setUnlocalizedName("sanctuaryStoneSword");
	public static Item aleris = (new RioVItem()).setUnlocalizedName("aleris");
	public static Item alerisHelmet = (new RioVArmor(AlerisArmorMaterial, render, 0, "aleris", false)).setUnlocalizedName("alerisHelmet");
	public static Item alerisChestplate = (new RioVArmor(AlerisArmorMaterial, render, 1, "aleris", false)).setUnlocalizedName("alerisChestplate");
	public static Item alerisLeggings = (new RioVArmor(AlerisArmorMaterial, render, 2, "aleris", false)).setUnlocalizedName("alerisLeggings");
	public static Item alerisBoots = (new RioVArmor(AlerisArmorMaterial, render, 3, "aleris", false)).setUnlocalizedName("alerisBoots");
	public static Item alerisPickaxe = (new RioVPickaxe(Aleris, false)).setUnlocalizedName("alerisPickaxe");
	public static Item alerisAxe = (new RioVAxe(Aleris, false)).setUnlocalizedName("alerisStoneAxe");
	public static Item alerisShovel = (new RioVSpade(Aleris, false)).setUnlocalizedName("alerisShovel");
	public static Item alerisSword = (new RioVWeapon(Aleris, false)).setUnlocalizedName("alerisSword");
	public static Item infusedVraviniteHelmet = (new RioVArmor(InfusedVraviniteArmorMaterial, render, 0, "vravinite", true)).setUnlocalizedName("infusedVraviniteHelmet");
	public static Item infusedVraviniteChestplate = (new RioVArmor(InfusedVraviniteArmorMaterial, render, 1, "vravinite", true)).setUnlocalizedName("infusedVraviniteChestplate");
	public static Item infusedVraviniteLeggings = (new RioVArmor(InfusedVraviniteArmorMaterial, render, 2, "vravinite", true)).setUnlocalizedName("infusedVraviniteLeggings");
	public static Item infusedVraviniteBoots = (new RioVArmor(InfusedVraviniteArmorMaterial, render, 3, "vravinite", true)).setUnlocalizedName("infusedVraviniteBoots");
	public static Item infusedVravinitePickaxe = (new RioVPickaxe(InfusedVravinite, true)).setUnlocalizedName("infusedVravinitePickaxe");
	public static Item infusedVraviniteAxe = (new RioVAxe(InfusedVravinite, true)).setUnlocalizedName("infusedVraviniteAxe");
	public static Item infusedVraviniteShovel = (new RioVSpade(InfusedVravinite, true)).setUnlocalizedName("infusedVraviniteShovel");
	public static Item infusedVraviniteSword = (new RioVWeapon(InfusedVravinite, true)).setUnlocalizedName("infusedVraviniteSword");
	public static Item voidHolder = (new RioVVoidHolder(Blocks.air)).setUnlocalizedName("voidHolder");
	public static Item voidHolderFilled = (new RioVVoidHolder(RioVBlocks.voidMoving)).setUnlocalizedName("voidHolder");
	public static Item berry = (new RioVConsumable(4, 0, false)).setUnlocalizedName("berry");
	public static Item blackBerry = (new RioVConsumable(4, 0, false)).setUnlocalizedName("blackBerry");
	public static Item jaavik = (new RioVItem()).setUnlocalizedName("jaavik");
	public static Item raspBerry = (new RioVConsumable(3, 0, false)).setUnlocalizedName("raspBerry");
	public static Item bloodBerry = (new RioVConsumable(6, 0, false)).setUnlocalizedName("bloodBerry");
	public static Item strawberry = (new RioVConsumable(3, 0, false)).setUnlocalizedName("strawBerry");
	public static Item chain = (new RioVItem()).setUnlocalizedName("chain");
	public static Item smallBag = (new RioVBag()).setUnlocalizedName("smallBag");
	public static Item mediumBag = (new RioVBag()).setUnlocalizedName("mediumBag");
	public static Item largeBag = (new RioVBag()).setUnlocalizedName("largeBag");
	public static Item sheenBag = (new RioVBag()).setUnlocalizedName("sheenBag");
	public static Item heart = (new RioVItem()).setUnlocalizedName("heart");
	public static Item supremeAunTunHelmet = (new RioVArmor(SupremeAunTunArmorMaterial, render, 0, "auntunminion", true)).setUnlocalizedName("supremeAunTunHelmet");
	public static Item supremeAunTunChestplate = (new RioVArmor(SupremeAunTunArmorMaterial, render, 1, "auntunminion", true)).setUnlocalizedName("supremeAunTunChestplate");
	public static Item supremeAunTunLeggings = (new RioVArmor(SupremeAunTunArmorMaterial, render, 2, "auntunminion", true)).setUnlocalizedName("supremeAunTunLeggings");
	public static Item supremeAunTunBoots = (new RioVArmor(SupremeAunTunArmorMaterial, render, 3, "auntunminion", true)).setUnlocalizedName("supremeAunTunBoots");
	public static Item ultraAxeOfAunTun = (new RioVWeapon(UltraAxeOfAunTun, true)).setUnlocalizedName("ultraAxeOfAunTun");
	public static Item tasaravHelmet = (new ItemTasaravHelmet(AlerisArmorMaterial, render, 0, "tasarav", false)).setUnlocalizedName("tasaravHelmet");
	public static Item tasaravChestplate = (new ItemTasaravChestplate(AlerisArmorMaterial, render, 1, "tasarav", false)).setUnlocalizedName("tasaravChestplate");
	public static Item tasaravLeggings = (new RioVArmor(AlerisArmorMaterial, render, 2, "tasarav", false)).setUnlocalizedName("tasaravLeggings");
	public static Item tasaravBoots = (new RioVArmor(AlerisArmorMaterial, render, 3, "tasarav", false)).setUnlocalizedName("tasaravBoots");
	public static Item tasaravSword = (new RioVWeapon(Aleris, false)).setUnlocalizedName("tasaravSword");
	public static Item paladinHelmet = (new RioVArmor(FlameArmorMaterial, render, 0, "paladin", false)).setUnlocalizedName("paladinHelmet");
	public static Item paladinChestplate = (new RioVArmor(FlameArmorMaterial, render, 1, "paladin", false)).setUnlocalizedName("paladinChestplate");
	public static Item paladinLeggings = (new RioVArmor(FlameArmorMaterial, render, 2, "paladin", false)).setUnlocalizedName("paladinLeggings");
	public static Item paladinBoots = (new RioVArmor(FlameArmorMaterial, render, 3, "paladin", false)).setUnlocalizedName("paladinBoots");
	public static Item paladinLongsword = (new RioVWeapon(InfusedOnyx, false)).setUnlocalizedName("paladinLongsword");
	public static Item graviWand = (new RioVWand(0, 1, 3)).setUnlocalizedName("graviWand");
	public static Item eosPotion = (new RioVDrinkable(0, 0, true)).setAlwaysEdible().setUnlocalizedName("eosPotion");
	public static Item guide = (new ItemGuide()).setUnlocalizedName("guide");

	public static void add()
	{		
		MethodUtil.registerItem(guide, "Guide");
		MethodUtil.registerItem(eosPotion, "Eos Potion");
		MethodUtil.registerItem(graviWand, "Gravi Wand");
		MethodUtil.registerItem(paladinHelmet, "Paladin Helmet");
		MethodUtil.registerItem(paladinChestplate, "Paladin Chestplate");
		MethodUtil.registerItem(paladinLeggings, "Paladin Leggings");
		MethodUtil.registerItem(paladinBoots, "Paladin Boots");
		MethodUtil.registerItem(paladinLongsword, "Paladin Longsword");
		MethodUtil.registerItem(tasaravHelmet, "Tasarav Mallor's Helmet");
		MethodUtil.registerItem(tasaravChestplate, "Tasarav Mallor's Chestplate");
		MethodUtil.registerItem(tasaravLeggings, "Tasarav Mallor's Leggings");
		MethodUtil.registerItem(tasaravBoots, "Tasarav Mallor's Boots");
		MethodUtil.registerItem(tasaravSword, "Tasarav Mallor's Sword");
		MethodUtil.registerItem(supremeAunTunHelmet, "Supreme Aun'Tun Helmet");
		MethodUtil.registerItem(supremeAunTunChestplate, "Supreme Aun'Tun Chestplate");
		MethodUtil.registerItem(supremeAunTunLeggings, "Supreme Aun'Tun Leggings");
		MethodUtil.registerItem(supremeAunTunBoots, "Supreme Aun'Tun Boots");
		MethodUtil.registerItem(heart, "Heart");
		MethodUtil.registerItem(ultraAxeOfAunTun, "Ultra Axe of Aun'Tun");
		MethodUtil.registerItem(sheenBag, "Sheen's Bag");
		MethodUtil.registerItem(largeBag, "Large Bag");
		MethodUtil.registerItem(mediumBag, "Medium Bag");
		MethodUtil.registerItem(smallBag, "Small Bag");
		MethodUtil.registerItem(blackBerry, "Blackberry");
		MethodUtil.registerItem(raspBerry, "Raspberry");
		MethodUtil.registerItem(bloodBerry, "Bloodberry");
		MethodUtil.registerItem(strawberry, "Strawberry");
		MethodUtil.registerItem(jaavik, "Jaavik");
		MethodUtil.registerItem(berry, "Berry");
		MethodUtil.registerItem(voidHolderFilled, "Void Liquid Holder Filled");
		MethodUtil.registerItem(voidHolder, "Void Liquid Holder");
		MethodUtil.registerItem(infusedVraviniteHelmet, "Infused Vravinite Helmet");
		MethodUtil.registerItem(infusedVraviniteChestplate, "Infused Vravinite Chestplate");
		MethodUtil.registerItem(infusedVraviniteLeggings, "Infused Vravinite Leggings");
		MethodUtil.registerItem(infusedVraviniteBoots, "Infused Vravinite Boots");
		MethodUtil.registerItem(infusedVravinitePickaxe, "Infused Vravinite Pickaxe");
		MethodUtil.registerItem(infusedVraviniteAxe, "Infused Vravinite Axe");
		MethodUtil.registerItem(infusedVraviniteShovel, "Infused Vravinite Shovel");
		MethodUtil.registerItem(infusedVraviniteSword, "Infused Vravinite Sword");
		MethodUtil.registerItem(alerisPickaxe, "Aleris Pickaxe");
		MethodUtil.registerItem(alerisAxe, "Aleris Axe");
		MethodUtil.registerItem(alerisShovel, "Aleris Shovel");
		MethodUtil.registerItem(alerisSword, "Aleris Sword");
		MethodUtil.registerItem(alerisHelmet, "Aleris Helmet");
		MethodUtil.registerItem(alerisChestplate, "Aleris Chestplate");
		MethodUtil.registerItem(alerisLeggings, "Aleris Leggings");
		MethodUtil.registerItem(alerisBoots, "Aleris Boots");
		MethodUtil.registerItem(aleris, "Aleris");
		MethodUtil.registerItem(sanctuaryStonePickaxe, "Sanctuary Stone Pickaxe");
		MethodUtil.registerItem(sanctuaryStoneAxe, "Sanctuary Stone Axe");
		MethodUtil.registerItem(sanctuaryStoneShovel, "Sanctuary Stone Shovel");
		MethodUtil.registerItem(sanctuaryStoneSword, "Sanctuary Stone Sword");
		MethodUtil.registerItem(skywoodPickaxe, "Skywood Pickaxe");
		MethodUtil.registerItem(skywoodAxe, "Skywood Axe");
		MethodUtil.registerItem(skywoodShovel, "Skywood Shovel");
		MethodUtil.registerItem(skywoodSword, "Skywood Sword");
		MethodUtil.registerItem(skywoodSticks, "Skywood Sticks");
		MethodUtil.registerItem(bloodPickaxe, "Blood Pickaxe");
		MethodUtil.registerItem(bloodAxe, "Blood Axe");
		MethodUtil.registerItem(bloodShovel, "Blood Shovel");
		MethodUtil.registerItem(bloodSword, "Blood Sword");
		MethodUtil.registerItem(bloodSticks, "Blood Sticks");
		MethodUtil.registerItem(skywoodDoorItem, "Skywood Door");
		MethodUtil.registerItem(bloodDoorItem, "Blood Door");
		MethodUtil.registerItem(sanctuatiteActivator, "Sanctuatite Activator");
		MethodUtil.registerItem(potionGlassSanctuatite, "Sanctuatite Potion");
		MethodUtil.registerItem(cherryBlossomDoorItem, "Cherry Blossom Door");
		MethodUtil.registerItem(cherryBlossomPickaxe, "Cherry Blossom Pickaxe");
		MethodUtil.registerItem(cherryBlossomAxe, "Cherry Blossom Axe");
		MethodUtil.registerItem(cherryBlossomShovel, "Cherry Blossom Shovel");
		MethodUtil.registerItem(cherryBlossomSword, "Cherry Blossom Sword");
		MethodUtil.registerItem(cherryBlossomSticks, "Cherry Blossom Sticks");
		MethodUtil.registerItem(fireballWand, "Fireball Wand");
		MethodUtil.registerItem(drakiuz, "Drakiuz");
		MethodUtil.registerItem(flamonorActivator, "Flamonor Activator");
		MethodUtil.registerItem(glimmerwoodDoorItem, "Glimmerwood Door");
		MethodUtil.registerItem(vraviniteHelmet, "Vravinite Helmet");
		MethodUtil.registerItem(vraviniteChestplate, "Vravinite Chestplate");
		MethodUtil.registerItem(vraviniteLeggings, "Vravinite Leggings");
		MethodUtil.registerItem(vraviniteBoots, "Vravinite Boots");
		MethodUtil.registerItem(vravinitePickaxe, "Vravinite Pickaxe");
		MethodUtil.registerItem(vraviniteAxe, "Vravinite Axe");
		MethodUtil.registerItem(vraviniteShovel, "Vravinite Shovel");
		MethodUtil.registerItem(vraviniteSword, "Vravinite Sword");
		MethodUtil.registerItem(vravinite, "Vravinite");
		MethodUtil.registerItem(vraviniteArrow, "Vravinite Arrow");
		MethodUtil.registerItem(vraviniteBow, "Vravinite Bow");
		MethodUtil.registerItem(blueMagicApple, "Magical Blue Apple");
		MethodUtil.registerItem(glimmerwoodPickaxe, "Glimmerwood Pickaxe");
		MethodUtil.registerItem(glimmerwoodAxe, "Glimmerwood Axe");
		MethodUtil.registerItem(glimmerwoodShovel, "Glimmerwood Shovel");
		MethodUtil.registerItem(glimmerwoodSword, "Glimmerwood Sword");
		MethodUtil.registerItem(glimmerwoodSticks, "Glimmerwood Sticks");
		MethodUtil.registerItem(vaerynActivator, "Vaeryn Activator");
		MethodUtil.registerItem(infusedBlindoniteHelmet, "Infused Blindonite Helmet");
		MethodUtil.registerItem(infusedBlindoniteChestplate, "Infused Blindonite Chestplate");
		MethodUtil.registerItem(infusedBlindoniteLeggings, "Infused Blindonite Leggings");
		MethodUtil.registerItem(infusedBlindoniteBoots, "Infused Blindonite Boots");
		MethodUtil.registerItem(infusedBlindonitePickaxe, "Infused Blindonite Pickaxe");
		MethodUtil.registerItem(infusedBlindoniteAxe, "Infused Blindonite Axe");
		MethodUtil.registerItem(infusedBlindoniteShovel, "Infused Blindonite Shovel");
		MethodUtil.registerItem(infusedBlindoniteSword, "Infused Blindonite Sword");
		MethodUtil.registerItem(blindoniteHelmet, "Blindonite Helmet");
		MethodUtil.registerItem(blindoniteChestplate, "Blindonite Chestplate");
		MethodUtil.registerItem(blindoniteLeggings, "Blindonite Leggings");
		MethodUtil.registerItem(blindoniteBoots, "Blindonite Boots");
		MethodUtil.registerItem(blindonitePickaxe, "Blindonite Pickaxe");
		MethodUtil.registerItem(blindoniteAxe, "Blindonite Axe");
		MethodUtil.registerItem(blindoniteShovel, "Blindonite Shovel");
		MethodUtil.registerItem(blindoniteSword, "Blindonite Sword");
		MethodUtil.registerItem(tefCrystal, "Tef Crystal");
		MethodUtil.registerItem(tefHelmet, "Tef's Legendary Helmet");
		MethodUtil.registerItem(tefChestplate, "Tef's Legendary Chestplate");
		MethodUtil.registerItem(tefLeggings, "Tef's Legendary Leggings");
		MethodUtil.registerItem(tefBoots, "Tef's Legendary Boots");
		MethodUtil.registerItem(blindOasisActivator, "Blind Oasis Activator");
		MethodUtil.registerItem(blindonite, "Blindonite");
		MethodUtil.registerItem(enforcedBowOfWurTun, "Enforced Bow Of Wur-Tun");
		MethodUtil.registerItem(helmetOfFlame, "Helmet of Flame");
		MethodUtil.registerItem(chestplateOfFlame, "Chestplate of Flame");
		MethodUtil.registerItem(leggingsOfFlame, "Leggings of Flame");
		MethodUtil.registerItem(bootsOfFlame, "Boots of Flame");
		MethodUtil.registerItem(ingotOfFlame, "Ingot of Flame");
		MethodUtil.registerItem(purpleFeather, "Purple Feather");
		MethodUtil.registerItem(clothOfMagic, "Cloth of Magic");
		MethodUtil.registerItem(swordOfFlame, "Sword of Flame");
		MethodUtil.registerItem(theDarknessCrystal, "Crystal of Darkness");
		MethodUtil.registerItem(magickaHelmet, "Hood of Magic");
		MethodUtil.registerItem(magickaChestplate, "Robe of Magic");
		MethodUtil.registerItem(magickaLeggings, "Leggings of Magic");
		MethodUtil.registerItem(magickaBoots, "Boots of Magic");
		MethodUtil.registerItem(galokinCrystal, "Galokin Crystal");
		MethodUtil.registerItem(galokinSword, "Galokin Sword");
		MethodUtil.registerItem(galokinHelmet, "Galokin Helmet");
		MethodUtil.registerItem(galokinChestplate, "Galokin Chestplate");
		MethodUtil.registerItem(galokinLeggings, "Galokin Leggings");
		MethodUtil.registerItem(galokinBoots, "Galokin Boots");
		MethodUtil.registerItem(vaiziCurrency, "Vaizi");
		MethodUtil.registerItem(cherry, "Cherry");
		MethodUtil.registerItem(manchet, "Manchet");
		MethodUtil.registerItem(pepper, "Pepper");
		MethodUtil.registerItem(pepperSpices, "Pepper Spices");
		MethodUtil.registerItem(spicedWine, "Spiced Wine");
		MethodUtil.registerItem(greenApple, "Green Apple");
		MethodUtil.registerItem(wine, "Wine");
		MethodUtil.registerItem(grapes, "Grapes");
		MethodUtil.registerItem(potionGlass, "Potion Glass");
		MethodUtil.registerItem(wineGlass, "Wine Glass");
		MethodUtil.registerItem(cookedHorseMeat, "Cooked Horse Meat");
		MethodUtil.registerItem(horseMeat, "Horse Meat");
		MethodUtil.registerItem(tomato, "Tomato");
		MethodUtil.registerItem(khuulisScythe, "Khuuli's Scythe");
		MethodUtil.registerItem(blackDurii, "Black Durii");
		MethodUtil.registerItem(auntunSummoner, "Aun'Tun Summoner");
		MethodUtil.registerItem(vulron, "Vulron");
		MethodUtil.registerItem(bowOfWurTun, "Bow of Wur-Tun");
		MethodUtil.registerItem(darknessArrow, "Arrow of Darkness");
		MethodUtil.registerItem(daetoriSword, "Daetori's Sword");
		MethodUtil.registerItem(sorrowSword, "Sorrow Sword");
		MethodUtil.registerItem(axeOfAunTun, "Axe of Aun'Tun");
		MethodUtil.registerItem(halfFusedAxeOfAunTun, "Half Fused Axe of Aun'Tun");
		MethodUtil.registerItem(unfusedAxeOfAunTun, "Unfused Axe of Aun'Tun");
		MethodUtil.registerItem(blackBone, "Black Bone");
		MethodUtil.registerItem(amethyst, "Amethyst");
		MethodUtil.registerItem(onyx, "Onyx");
		MethodUtil.registerItem(slateFragment, "Slate Fragment");
		MethodUtil.registerItem(orb, "Orb");
		MethodUtil.registerItem(nironite, "Nironite");
		MethodUtil.registerItem(agonite, "Agonite");
		MethodUtil.registerItem(terronCrystal, "Terron Crystal");
		MethodUtil.registerItem(baseCrystal, "Base Crystal");
		MethodUtil.registerItem(garnet, "Garnet");
		MethodUtil.registerItem(infusedAmethystShovel, "Infused Amethyst Shovel");
		MethodUtil.registerItem(infusedAmethystPickaxe, "Infused Amethyst Pickaxe");
		MethodUtil.registerItem(infusedAmethystAxe, "Infused Amethyst Axe");
		MethodUtil.registerItem(infusedOnyxShovel, "Infused Onyx Shovel");
		MethodUtil.registerItem(infusedOnyxPickaxe, "Infused Onyx Pickaxe");
		MethodUtil.registerItem(infusedOnyxAxe, "Infused Onyx Axe");
		MethodUtil.registerItem(auntunHelmet, "Aun'Tun Minion Helmet");
		MethodUtil.registerItem(auntunChestplate, "Aun'Tun Minion Chestplate");
		MethodUtil.registerItem(auntunLeggings, "Aun'Tun Minion Leggings");
		MethodUtil.registerItem(auntunBoots, "Aun'Tun Minion Boots");
		MethodUtil.registerItem(onyxHelmet, "Onyx Helmet");
		MethodUtil.registerItem(onyxChestplate, "Onyx Chestplate");
		MethodUtil.registerItem(onyxLeggings, "Onyx Leggings");
		MethodUtil.registerItem(onyxBoots, "Onyx Boots");
		MethodUtil.registerItem(amethystHelmet, "Amethyst Helmet");
		MethodUtil.registerItem(amethystChestplate, "Amethyst Chestplate");
		MethodUtil.registerItem(amethystLeggings, "Amethyst Leggings");
		MethodUtil.registerItem(amethystBoots, "Amethyst Boots");
		MethodUtil.registerItem(infusedOnyxHelmet, "Infused Onyx Helmet");
		MethodUtil.registerItem(infusedOnyxChestplate, "Infused Onyx Chestplate");
		MethodUtil.registerItem(infusedOnyxLeggings, "Infused Onyx Leggings");
		MethodUtil.registerItem(infusedOnyxBoots, "Infused Onyx Boots");
		MethodUtil.registerItem(infusedAmethystHelmet, "Infused Amethyst Helmet");
		MethodUtil.registerItem(infusedAmethystChestplate, "Infused Amethyst Chestplate");
		MethodUtil.registerItem(infusedAmethystLeggings, "Infused Amethyst Leggings");
		MethodUtil.registerItem(infusedAmethystBoots, "Infused Amethyst Boots");
		MethodUtil.registerItem(amethystPickaxe, "Amethyst Pickaxe");
		MethodUtil.registerItem(amethystAxe, "Amethyst Axe");
		MethodUtil.registerItem(amethystShovel, "Amethyst Shovel");
		MethodUtil.registerItem(amethystSword, "Amethyst Sword");
		MethodUtil.registerItem(infusedAmethystSword, "Infused Amethyst Sword");
		MethodUtil.registerItem(onyxSword, "Onyx Sword");
		MethodUtil.registerItem(infusedOnyxSword, "Infused Onyx Sword");
		MethodUtil.registerItem(onyxPickaxe, "Onyx Pickaxe");
		MethodUtil.registerItem(agonitePickaxe, "Agonite Pickaxe");
		MethodUtil.registerItem(onyxAxe, "Onyx Axe");
		MethodUtil.registerItem(onyxShovel, "Onyx Shovel");
		MethodUtil.registerItem(garnetHelmet, "Garnet Helmet");
		MethodUtil.registerItem(garnetChestplate, "Garnet Chestplate");
		MethodUtil.registerItem(garnetLeggings, "Garnet Leggings");
		MethodUtil.registerItem(garnetBoots, "Garnet Boots");
		MethodUtil.registerItem(mythrilHelmet, "Mythril Helmet");
		MethodUtil.registerItem(mythrilChestplate, "Mythril Chestplate");
		MethodUtil.registerItem(mythrilLeggings, "Mythril Leggings");
		MethodUtil.registerItem(mythrilBoots, "Mythril Boots");
		MethodUtil.registerItem(darkMatter, "Dark Matter");
		MethodUtil.registerItem(ambrosia, "Ambrosia");
		MethodUtil.registerItem(mythrilIngot, "Mythril Ingot");
		MethodUtil.registerItem(burnedQuartz, "Black Quartz");
		MethodUtil.registerItem(dragonSword, "Dragon Sword");
		MethodUtil.registerItem(dragonSoul, "Dragon Soul Gem");
		MethodUtil.registerItem(demonAngelCrystal, "Demon Angel Crystal");
		MethodUtil.registerItem(dragonHelmet, "Dragon Helmet");
		MethodUtil.registerItem(dragonChestplate, "Dragon Chestplate");
		MethodUtil.registerItem(dragonLeggings, "Dragon Leggings");
		MethodUtil.registerItem(dragonBoots, "Dragon Boots");
		MethodUtil.registerItem(dragonPickaxe, "Dragon Pickaxe");
		MethodUtil.registerItem(dragonAxe, "Dragon Axe");
		MethodUtil.registerItem(dragonShovel, "Dragon Shovel");
		MethodUtil.registerItem(infusedDragonHelmet, "Infused Dragon Helmet");
		MethodUtil.registerItem(infusedDragonChestplate, "Infused Dragon Chestplate");
		MethodUtil.registerItem(infusedDragonLeggings, "Infused Dragon Leggings");
		MethodUtil.registerItem(infusedDragonBoots, "Infused Dragon Boots");
		MethodUtil.registerItem(infusedDragonPickaxe, "Infused Dragon Pickaxe");
		MethodUtil.registerItem(infusedDragonAxe, "Infused Dragon Axe");
		MethodUtil.registerItem(infusedDragonShovel, "Infused Dragon Shovel");
		MethodUtil.registerItem(infusedDragonSword, "Infused Dragon Sword");
	}

	public static Item infusedBloodwoodPickaxe;
	public static Item infusedBloodwoodAxe;
	public static Item infusedBloodwoodShovel;
	public static Item infusedBloodwoodSword;
	public static Item infusedGhostwoodSword;
	public static Item infusedGhostwoodPickaxe;
	public static Item infusedGhostwoodShovel;
	public static Item infusedGhostwoodAxe;
	public static Item infusedDarkwoodSword;
	public static Item infusedDarkwoodPickaxe;
	public static Item infusedDarkwoodShovel;
	public static Item infusedDarkwoodAxe;
	public static Item infusedFusewoodSword;
	public static Item infusedFusewoodPickaxe;
	public static Item infusedFusewoodShovel;
	public static Item infusedFusewoodAxe;
	public static Item infusedNetherquartzSword;
	public static Item infusedNetherquartzPickaxe;
	public static Item infusedNetherquartzShovel;
	public static Item infusedNetherquartzAxe;

	public static void addNatura()
	{
		/**
		if(TheMistsOfRioV.getInstance().natura)
		{
			ToolMaterial InfusedBloodwood = EnumHelper.addToolMaterial("InfusedBloodwood", 3, 450, 8.0F, 4.0F, 25);
			ToolMaterial InfusedGhostwood = EnumHelper.addToolMaterial("InfusedGhostwood", 1, 159, 3.0F, 1.0F, 16);
			ToolMaterial InfusedDarkwood = EnumHelper.addToolMaterial("InfusedDarkwood", 2, 231, 5.0F, 2.0F, 6);

			infusedBloodwoodPickaxe = (new RioVPickaxe(Config.addExpansionItem("Infused Bloodwood Pickaxe"), InfusedBloodwood, true)).setUnlocalizedName("Natura:bloodwood_pickaxe");
			infusedBloodwoodAxe = (new RioVAxe(Config.addExpansionItem("Infused Bloodwood Axe"), InfusedBloodwood, true)).setUnlocalizedName("Natura:bloodwood_hatchet");
			infusedBloodwoodShovel = (new RioVSpade(Config.addExpansionItem("Infused Bloodwood Shovel"), InfusedBloodwood, true)).setUnlocalizedName("Natura:bloodwood_shovel");
			infusedBloodwoodSword = (new RioVWeapon(Config.addExpansionItem("Infused Bloodwood Sword"), InfusedBloodwood, true)).setUnlocalizedName("Natura:bloodwood_sword");
			infusedGhostwoodPickaxe = (new RioVPickaxe(Config.addExpansionItem("Infused Ghostwood Pickaxe"), InfusedBloodwood, true)).setUnlocalizedName("Natura:ghostwood_pickaxe");
			infusedGhostwoodAxe = (new RioVAxe(Config.addExpansionItem("Infused Ghostwood Axe"), InfusedBloodwood, true)).setUnlocalizedName("Natura:ghostwood_hatchet");
			infusedGhostwoodShovel = (new RioVSpade(Config.addExpansionItem("Infused Ghostwood Shovel"), InfusedBloodwood, true)).setUnlocalizedName("Natura:ghostwood_shovel");
			infusedGhostwoodSword = (new RioVWeapon(Config.addExpansionItem("Infused Ghostwood Sword"), InfusedBloodwood, true)).setUnlocalizedName("Natura:ghostwood_sword");
			infusedDarkwoodPickaxe = (new RioVPickaxe(Config.addExpansionItem("Infused Darkwood Pickaxe"), InfusedBloodwood, true)).setUnlocalizedName("Natura:darkwood_pickaxe");
			infusedDarkwoodAxe = (new RioVAxe(Config.addExpansionItem("Infused Darkwood Axe"), InfusedBloodwood, true)).setUnlocalizedName("Natura:darkwood_hatchet");
			infusedDarkwoodShovel = (new RioVSpade(Config.addExpansionItem("Infused Darkwood Shovel"), InfusedBloodwood, true)).setUnlocalizedName("Natura:darkwood_shovel");
			infusedDarkwoodSword = (new RioVWeapon(Config.addExpansionItem("Infused Darkwood Sword"), InfusedBloodwood, true)).setUnlocalizedName("Natura:darkwood_sword");
			infusedFusewoodPickaxe = (new RioVPickaxe(Config.addExpansionItem("Infused Fusewood Pickaxe"), InfusedBloodwood, true)).setUnlocalizedName("Natura:fusewood_pickaxe");
			infusedFusewoodAxe = (new RioVAxe(Config.addExpansionItem("Infused Fusewood Axe"), InfusedBloodwood, true)).setUnlocalizedName("Natura:fusewood_hatchet");
			infusedFusewoodShovel = (new RioVSpade(Config.addExpansionItem("Infused Fusewood Shovel"), InfusedBloodwood, true)).setUnlocalizedName("Natura:fusewood_shovel");
			infusedFusewoodSword = (new RioVWeapon(Config.addExpansionItem("Infused Fusewood Sword"), InfusedBloodwood, true)).setUnlocalizedName("Natura:fusewood_sword");
			infusedNetherquartzPickaxe = (new RioVPickaxe(Config.addExpansionItem("Infused Netherquartz Pickaxe"), InfusedBloodwood, true)).setUnlocalizedName("Natura:netherquartz_pickaxe");
			infusedNetherquartzAxe = (new RioVAxe(Config.addExpansionItem("Infused Netherquartz Axe"), InfusedBloodwood, true)).setUnlocalizedName("Natura:netherquartz_hatchet");
			infusedNetherquartzShovel = (new RioVSpade(Config.addExpansionItem("Infused Netherquartz Shovel"), InfusedBloodwood, true)).setUnlocalizedName("Natura:netherquartz_shovel");
			infusedNetherquartzSword = (new RioVWeapon(Config.addExpansionItem("Infused Netherquartz Sword"), InfusedBloodwood, true)).setUnlocalizedName("Natura:netherquartz_sword");

			MethodUtil.registerItem(infusedFusewoodPickaxe, "Infused Fusewood Pickaxe");
			MethodUtil.registerItem(infusedFusewoodAxe, "Infused Fusewood Axe");
			MethodUtil.registerItem(infusedFusewoodShovel, "Infused Fusewood Shovel");
			MethodUtil.registerItem(infusedFusewoodSword, "Infused Fusewood Sword");
			MethodUtil.registerItem(infusedNetherquartzPickaxe, "Infused Netherquartz Pickaxe");
			MethodUtil.registerItem(infusedNetherquartzAxe, "Infused Netherquartz Axe");
			MethodUtil.registerItem(infusedNetherquartzShovel, "Infused Netherquartz Shovel");
			MethodUtil.registerItem(infusedNetherquartzSword, "Infused Netherquartz Sword");
			MethodUtil.registerItem(infusedBloodwoodPickaxe, "Infused Bloodwood Pickaxe");
			MethodUtil.registerItem(infusedBloodwoodAxe, "Infused Bloodwood Axe");
			MethodUtil.registerItem(infusedBloodwoodShovel, "Infused Bloodwood Shovel");
			MethodUtil.registerItem(infusedBloodwoodSword, "Infused Bloodwood Sword");
			MethodUtil.registerItem(infusedGhostwoodPickaxe, "Infused Ghostwood Pickaxe");
			MethodUtil.registerItem(infusedGhostwoodAxe, "Infused Ghostwood Axe");
			MethodUtil.registerItem(infusedGhostwoodShovel, "Infused Ghostwood Shovel");
			MethodUtil.registerItem(infusedGhostwoodSword, "Infused Ghostwood Sword");
			MethodUtil.registerItem(infusedDarkwoodPickaxe, "Infused Darkwood Pickaxe");
			MethodUtil.registerItem(infusedDarkwoodAxe, "Infused Darkwood Axe");
			MethodUtil.registerItem(infusedDarkwoodShovel, "Infused Darkwood Shovel");
			MethodUtil.registerItem(infusedDarkwoodSword, "Infused Darkwood Sword");
		}
		 **/
	}

	public static Item infusedSkyrootPickaxe;
	public static Item infusedSkyrootAxe;
	public static Item infusedSkyrootShovel;
	public static Item infusedSkyrootSword;
	public static Item infusedHolystonePickaxe;
	public static Item infusedHolystoneAxe;
	public static Item infusedHolystoneShovel;
	public static Item infusedHolystoneSword;
	public static Item infusedZanitePickaxe;
	public static Item infusedZaniteAxe;
	public static Item infusedZaniteShovel;
	public static Item infusedZaniteSword;
	public static Item infusedGravititePickaxe;
	public static Item infusedGravititeAxe;
	public static Item infusedGravititeShovel;
	public static Item infusedGravititeSword;
	public static Item infusedZaniteHelmet;
	public static Item infusedZaniteChestplate;
	public static Item infusedZaniteLeggings;
	public static Item infusedZaniteBoots;
	public static Item infusedGravititeHelmet;
	public static Item infusedGravititeChestplate;
	public static Item infusedGravititeLeggings;
	public static Item infusedGravititeBoots;
	public static Item magicalBlueBerry;

	public static void addAether()
	{
		/**
		if(TheMistsOfRioV.getInstance().aether)
		{
			ToolMaterial InfusedSkyroot = EnumHelper.addToolMaterial("InfusedSkyroot", 1, 159, 3.0F, 1.0F, 16);
			ToolMaterial InfusedHolystone = EnumHelper.addToolMaterial("InfusedHolystone", 2, 231, 5.0F, 2.0F, 6);
			ToolMaterial InfusedZanite = EnumHelper.addToolMaterial("InfusedZanite", 3, 350, 7.0F, 3.0F, 15);
			ToolMaterial InfusedGravitite = EnumHelper.addToolMaterial("InfusedGravitite", 4, 1661, 9.0F, 4.0F, 11);

			ArmorMaterial InfusedZaniteArmor = EnumHelper.addArmorMaterial("InfusedZaniteArmor", 17, new int[]{3, 6, 5, 3}, 11);
			ArmorMaterial InfusedGravititeArmor = EnumHelper.addArmorMaterial("InfusedGravititeArmor", 35, new int[]{4, 8, 6, 4}, 12);

			infusedSkyrootPickaxe = (new RioVPickaxe(Config.addExpansionItem("Infused Skyroot Pickaxe"), InfusedSkyroot, true)).setUnlocalizedName("infusedSkyrootPickaxe");
			infusedSkyrootAxe = (new RioVAxe(Config.addExpansionItem("Infused Skyroot Axe"), InfusedSkyroot, true)).setUnlocalizedName("infusedSkyrootAxe");
			infusedSkyrootShovel = (new RioVSpade(Config.addExpansionItem("Infused Skyroot Shovel"), InfusedSkyroot, true)).setUnlocalizedName("infusedSkyrootShovel");
			infusedSkyrootSword = (new RioVWeapon(Config.addExpansionItem("Infused Skyroot Sword"), InfusedSkyroot, true)).setUnlocalizedName("infusedSkyrootSword");
			infusedHolystonePickaxe = (new RioVPickaxe(Config.addExpansionItem("Infused Holystone Pickaxe"), InfusedHolystone, true)).setUnlocalizedName("infusedHolystonePickaxe");
			infusedHolystoneAxe = (new RioVAxe(Config.addExpansionItem("Infused Holystone Axe"), InfusedHolystone, true)).setUnlocalizedName("infusedHolystoneAxe");
			infusedHolystoneShovel = (new RioVSpade(Config.addExpansionItem("Infused Holystone Shovel"), InfusedHolystone, true)).setUnlocalizedName("infusedHolystoneShovel");
			infusedHolystoneSword = (new RioVWeapon(Config.addExpansionItem("Infused Holystone Sword"), InfusedHolystone, true)).setUnlocalizedName("infusedHolystoneSword");
			infusedZanitePickaxe = (new RioVPickaxe(Config.addExpansionItem("Infused Zanite Pickaxe"), InfusedZanite, true)).setUnlocalizedName("infusedZanitePickaxe");
			infusedZaniteAxe = (new RioVAxe(Config.addExpansionItem("Infused Zanite Axe"), InfusedZanite, true)).setUnlocalizedName("infusedZaniteAxe");
			infusedZaniteShovel = (new RioVSpade(Config.addExpansionItem("Infused Zanite Shovel"), InfusedZanite, true)).setUnlocalizedName("infusedZaniteShovel");
			infusedZaniteSword = (new RioVWeapon(Config.addExpansionItem("Infused Zanite Sword"), InfusedZanite, true)).setUnlocalizedName("infusedZaniteSword");
			infusedGravititePickaxe = (new RioVPickaxe(Config.addExpansionItem("Infused Gravitite Pickaxe"), InfusedGravitite, true)).setUnlocalizedName("infusedGravititePickaxe");
			infusedGravititeAxe = (new RioVAxe(Config.addExpansionItem("Infused Gravitite Axe"), InfusedGravitite, true)).setUnlocalizedName("infusedGravititeAxe");
			infusedGravititeShovel = (new RioVSpade(Config.addExpansionItem("Infused Gravitite Shovel"), InfusedGravitite, true)).setUnlocalizedName("infusedGravititeShovel");
			infusedGravititeSword = (new RioVWeapon(Config.addExpansionItem("Infused Gravitite Sword"), InfusedGravitite, true)).setUnlocalizedName("infusedGravititeSword");
			infusedZaniteHelmet = (new RioVArmor(Config.addExpansionItem("Infused Zanite Helmet"), InfusedZaniteArmor, render, 0, "Zanite", true)).setUnlocalizedName("infusedZaniteHelmet");
			infusedZaniteChestplate = (new RioVArmor(Config.addExpansionItem("Infused Zanite Chestplate"), InfusedZaniteArmor, render, 1, "Zanite", true)).setUnlocalizedName("infusedZaniteChestplate");
			infusedZaniteLeggings = (new RioVArmor(Config.addExpansionItem("Infused Zanite Leggings"), InfusedZaniteArmor, render, 2, "Zanite", true)).setUnlocalizedName("infusedZaniteLeggings");
			infusedZaniteBoots = (new RioVArmor(Config.addExpansionItem("Infused Zanite Boots"), InfusedZaniteArmor, render, 3, "Zanite", true)).setUnlocalizedName("infusedZaniteBoots");
			infusedGravititeHelmet = (new RioVArmor(Config.addExpansionItem("Infused Gravitite Helmet"), InfusedGravititeArmor, render, 0, "Gravitite", true)).setUnlocalizedName("infusedGravitieHelmet");
			infusedGravititeChestplate = (new RioVArmor(Config.addExpansionItem("Infused Gravitite Chestplate"), InfusedGravititeArmor, render, 1, "Gravitite", true)).setUnlocalizedName("infusedGravitieChestplate");
			infusedGravititeLeggings = (new RioVArmor(Config.addExpansionItem("Infused Gravitite Leggings"), InfusedGravititeArmor, render, 2, "Gravitite", true)).setUnlocalizedName("infusedGravitieLeggings");
			infusedGravititeBoots = (new RioVArmor(Config.addExpansionItem("Infused Gravitite Boots"), InfusedGravititeArmor, render, 3, "Gravitite", true)).setUnlocalizedName("infusedGravitieBoots");
			magicalBlueBerry = (new RioVConsumable(Config.addExpansionItem("Magical Blue Berry"), 6, 0, true)).setUnlocalizedName("magicalBlueBerry");

			MethodUtil.registerItem(infusedZaniteHelmet, "Infused Zanite Helmet");
			MethodUtil.registerItem(infusedZaniteChestplate, "Infused Zanite Chestplate");
			MethodUtil.registerItem(infusedZaniteLeggings, "Infused Zanite Leggings");
			MethodUtil.registerItem(infusedZaniteBoots, "Infused Zanite Boots");
			MethodUtil.registerItem(infusedGravititeHelmet, "Infused Gravitite Helmet");
			MethodUtil.registerItem(infusedGravititeChestplate, "Infused Gravitite Chestplate");
			MethodUtil.registerItem(infusedGravititeLeggings, "Infused Gravitite Leggings");
			MethodUtil.registerItem(infusedGravititeBoots, "Infused Gravitite Boots");
			MethodUtil.registerItem(infusedSkyrootPickaxe, "Infused Skyroot Pickaxe");
			MethodUtil.registerItem(infusedSkyrootAxe, "Infused Skyroot Axe");
			MethodUtil.registerItem(infusedSkyrootShovel, "Infused Skyroot Shovel");
			MethodUtil.registerItem(infusedSkyrootSword, "Infused Skyroot Sword");
			MethodUtil.registerItem(infusedHolystonePickaxe, "Infused Holystone Pickaxe");
			MethodUtil.registerItem(infusedHolystoneAxe, "Infused Holystone Axe");
			MethodUtil.registerItem(infusedHolystoneShovel, "Infused Holystone Shovel");
			MethodUtil.registerItem(infusedHolystoneSword, "Infused Holystone Sword");
			MethodUtil.registerItem(infusedZanitePickaxe, "Infused Zanite Pickaxe");
			MethodUtil.registerItem(infusedZaniteAxe, "Infused Zanite Axe");
			MethodUtil.registerItem(infusedZaniteShovel, "Infused Zanite Shovel");
			MethodUtil.registerItem(infusedZaniteSword, "Infused Zanite Sword");
			MethodUtil.registerItem(infusedGravititePickaxe, "Infused Gravitite Pickaxe");
			MethodUtil.registerItem(infusedGravititeAxe, "Infused Gravitite Axe");
			MethodUtil.registerItem(infusedGravititeShovel, "Infused Gravitite Shovel");
			MethodUtil.registerItem(infusedGravititeSword, "Infused Gravitite Sword");
			MethodUtil.registerItem(magicalBlueBerry, "Magical Blue Berry");
		}**/
	}
}
